import { RingPosition, Ring } from './ring';
import { MoveHistory, RingGroupType } from './movement';
import { Controls } from './controls';
declare type CursorMode = RingGroupType;
export declare class Cursor {
    type: CursorMode;
    pos: RingPosition;
    private state_;
    private currentMovement_;
    private animatingMovement_;
    private readonly animation_;
    private readonly ring_;
    private readonly moveHistory_;
    private readonly controls_;
    constructor(ring: Ring, moveHistory: MoveHistory, controls: Controls);
    get hidden(): boolean;
    get focused(): boolean;
    switchType(): void;
    sectionSelected(type: CursorMode, index: number): boolean;
    cellSelected({ th, r }: RingPosition): boolean;
    move(reverse: boolean, animate?: boolean): void;
    private drawAnimationFrame;
    draw(anim_amount?: number, ctx?: CanvasRenderingContext2D): void;
    private drawRing_;
    private drawRow_;
    hide(): void;
    show(): void;
    isBusy(): boolean;
    onKeyDown(event: KeyboardEvent): void;
    private confirm;
    cancel(): void;
    private cancelPlanned;
    private undo;
    private switchFocus;
    private updateControls;
    private moveRing;
    private arrowIsPositive;
}
export {};
